"""Render the twelve scenes and write ../category-art.tsx.

    python3 build.py                  # regenerate the component
    python3 build.py --preview DIR    # also write a contact sheet + 4x PNGs to DIR (needs rsvg-convert)

Pure Python, no dependencies. Edit scenes.py, re-run, commit the TSX.
"""
import os, subprocess, sys, time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from iso import emit  # noqa: E402
from scenes import SCENES  # noqa: E402

SW = 1.25          # the one stroke weight
SEC = 0.45         # secondary-line opacity
DASH = "2 2.5"     # hidden / guide lines
TSX = os.path.join(HERE, "..", "category-art.tsx")

args = sys.argv[1:]
preview = args[args.index("--preview") + 1] if "--preview" in args else None

results = {}
for slug, fn in SCENES.items():
    t = time.time()
    segs, dots = fn().render()
    paths, dd, _ = emit(segs, dots)
    results[slug] = (paths, dd)
    size = sum(len(v) for v in paths.values())
    print(f"{slug:18s} {size:5d} B  {time.time() - t:.1f}s", file=sys.stderr)


def jsx(paths, dd):
    out = []
    if "p" in paths:
        out.append(f'<path d="{paths["p"]}" />')
    if "s" in paths:
        out.append(f'<path d="{paths["s"]}" strokeOpacity={{SECONDARY}} />')
    if "d" in paths:
        out.append(f'<path d="{paths["d"]}" strokeOpacity={{SECONDARY}} strokeDasharray="{DASH}" />')
    for (x, y), r in dd:
        out.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{r}" fill="currentColor" stroke="none" />')
    return "\n      ".join(out)


HEADER = '''// One monoline illustration per register category — the lab record page's
// header art (owner, 2026-09-15: "maybe add SVG illustration based on the
// category"). CONTRACT (both lab designers build against it):
//   <CategoryArt category={p.category} className="…" />
//   · inline SVG, viewBox "0 0 240 160", decorative (aria-hidden)
//   · strokes only, `currentColor`, so the page sets the gray via `color`
//   · unknown category → the `other` drawing, never nothing
//
// GENERATED by _gen/build.py from _gen/scenes.py — do not hand-edit the path
// data; change the scene and re-run `python3 web/lib/art/_gen/build.py`.
// Style rules the generator enforces: true isometric projection (30°), hidden
// lines removed exactly, one stroke weight (1.25), round caps and joins, a
// lighter opacity for secondary lines, dashes only for hidden/guide lines, and
// every drawing scaled into the same footprint around the viewBox centre.
import type { ReactElement } from "react";

const SECONDARY = %s;

const ART: Record<string, ReactElement> = {
%s
};

export function CategoryArt({ category, className }: { category: string; className?: string }) {
  const art = Object.prototype.hasOwnProperty.call(ART, category) ? ART[category] : ART.other;
  return (
    <svg
      className={className}
      viewBox="0 0 240 160"
      width="240"
      height="160"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.25"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      data-category={category}
    >
      {art}
    </svg>
  );
}
'''

body = []
for n, (paths, dd) in results.items():
    key = n if n.replace("_", "").isalnum() else f'"{n}"'
    body.append(f"  {key}: (\n    <>\n      {jsx(paths, dd)}\n    </>\n  ),")
open(TSX, "w").write(HEADER % (SEC, "\n".join(body)))
print(f"wrote {os.path.normpath(TSX)} ({os.path.getsize(TSX)} B)", file=sys.stderr)

if preview:
    def svg_inner(paths, dd):
        out = []
        if "p" in paths:
            out.append(f'<path d="{paths["p"]}"/>')
        if "s" in paths:
            out.append(f'<path d="{paths["s"]}" stroke-opacity="{SEC}"/>')
        if "d" in paths:
            out.append(f'<path d="{paths["d"]}" stroke-opacity="{SEC}" stroke-dasharray="{DASH}"/>')
        for (x, y), r in dd:
            out.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{r}" fill="currentColor" stroke="none"/>')
        return "".join(out)

    os.makedirs(os.path.join(preview, "z"), exist_ok=True)
    g = f'color="#8a8c93" fill="none" stroke="currentColor" stroke-width="{SW}" stroke-linecap="round" stroke-linejoin="round"'
    cols, cw, ch = 4, 260, 190
    names = list(results)
    rows = (len(names) + cols - 1) // cols
    sheet = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{cols*cw}" height="{rows*ch}"><rect width="100%" height="100%" fill="#fff"/>']
    for i, n in enumerate(names):
        x, y = (i % cols) * cw + 10, (i // cols) * ch + 6
        sheet.append(f'<g transform="translate({x},{y})" {g}><rect width="240" height="160" stroke="#eee" stroke-width="1"/>{svg_inner(*results[n])}</g>'
                     f'<text x="{x}" y="{y+176}" font-family="Helvetica" font-size="11" fill="#8a8c93">{n}</text>')
        p = os.path.join(preview, "z", n + ".svg")
        open(p, "w").write(f'<svg xmlns="http://www.w3.org/2000/svg" width="240" height="160" {g}><rect width="240" height="160" fill="#fff" stroke="none"/>{svg_inner(*results[n])}</svg>')
        subprocess.run(["rsvg-convert", "-z", "4", p, "-o", p[:-4] + ".png"], check=True)
    sheet.append("</svg>")
    sp = os.path.join(preview, "sheet.svg")
    open(sp, "w").write("".join(sheet))
    subprocess.run(["rsvg-convert", "-z", "2", sp, "-o", os.path.join(preview, "sheet.png")], check=True)
